config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  root to: 'tasklists#index'
  resources :tasklists
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tasklist.rb
class Tasklist < ApplicationRecord
  belongs_to :user

  validates :status, presence: true, length: {maximum: 10}
  validates :content, presence: true, length: {maximum:255}
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :tasklists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
    
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_microposts = user.microposts.count
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # p "*************"
    # p params.keys
    # p "*************"
    # p params[:session]
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
end

private

def login(email, password)
  @user = User.find_by(email: email)
  if @user && @user.authenticate(password)
    #ログイン成功
    session[:user_id] = @user.id
    return true
  else
    #ログイン失敗
    return false
  end
end

app/controllers/tasklists_controller.rb
class TasklistsController < ApplicationController
  before_action :require_user_logged_in, only: [:new, :create]
  before_action :set_tasklist, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  
  def index
    if logged_in?
      @user = current_user
      @tasklists = current_user.tasklists.order('created_at DESC').page(params[:page])
    end
    #不要だよね？@tasklists = Tasklist.all.page(params[:page])
  end
  
  def show
  end
  
  def new
    @tasklist = Tasklist.new
  end
  
  def create
    # p "**************"
    # p params
    @tasklist = current_user.tasklists.build(tasklist_params)
    #@tasklist = Tasklist.new(tasklist_params)
    
    if @tasklist.save
      flash[:success] = " Tasklist　が正常に投稿されました"
      redirect_to root_url
    else
      flash.now[:danger] = 'Tasklist　が投稿に失敗しました'
      render :new
    end
  end
  
  def edit
  end
  
  def update
    
    if @tasklist.update(tasklist_params)
      flash[:success] = 'Tasklist は正常に更新されました'
      redirect_to @tasklist
      
    else
      flash.now[:danger] = 'Tasklist は更新されませんでした'
      render :edit
    end
  end
  
  def destroy
    # before action系のことを書かなくてはいけない
    # くわしくはmicropostsのdestroyのところを参考
    
    @tasklist.destroy
     flash[:success] = 'Taskは正常に削除されました'
    redirect_to tasklists_url
  end
  
  private
  
  def set_tasklist
    @tasklist = Tasklist.find(params[:id])
  end

  # Strong Parameter
  def tasklist_params
     params.require(:tasklist).permit(:content, :status)
  end

  def correct_user
    redirect_to root_url if @tasklist.user != current_user
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save!
      flash[:success] = 'ユーザを登録しました'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザー登録に失敗しました'
      render :new
    end
  end
    #成功時は redirect_to root_url
    # user#indexとuser#showは不要なので削除


private
#strong parameter
def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
end

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/tasklists_helper.rb
module TasklistsHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options ={size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
      "https://secure.gravatar.com/avatar/
      #{gravatar_id}
      ?s=
      #{size}
      "
    end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? >
  
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
      
        <li>
          <%= message %>
        </li>
        
      <% end %>
      
        </ul>
      </div>
    <% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>

  <div class="alert alert-
  <%= message_type %>
  ">
<%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded-"false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Tasklist</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          
          <% if logged_in? %>
            <li>
              <%#= link_to 'Users', users_path %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <%= current_user.name %>
                   <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%#= link_to 'My profile', user_path(current_user) %>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                  <%= link_to '新規タスクの投稿', new_tasklist_path %>
                </li>
                <li>
                  <%= link_to 'Logout', logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          
<% else %>
        <li>
         <%= link_to 'Signup', signup_path %>
        </li> 
        <li>
          <%= link_to 'login', login_path %>
        </li>
<% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>KadaiTasklist</title>
    <%= csrf_meta_tags %>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  </head>

  <body>
    
<%= render 'layouts/navbar' %>
    <div class="container">
      
<%= render 'layouts/flash_messages' %>
    
<%= yield %>
    </div>
    <%#= debug params %>
  </body>
</html>

app/views/tasklists/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
    


<%= form_for(tasklist) do |f| %>

<% if tasklist.errors.any? %>

    <div id="error_explanation", class="alert-warning">
      <ul>
        
<% tasklist.errors.full_messages.each do |message| %>

          <li>
<%= message %>
</li>
        
<% end %>

      </ul>
    </div>
  
<% end %>

<div class="form-group">
<%= f.label :content,'タスク' %>

<%= f.text_field :content, class: 'form-control' %>
</div>

<div class="form-group">
<%= f.label :status, 'ステータス' %>

<%= f.text_field :status, class: 'form-control' %>
</div>

<%= f.submit '追加', class: 'btn btn-primary' %>

<% end %>

  </div>
</div>

app/views/tasklists/_tasklists.html.erb
<ul class="media-list">
  <% tasklists.each do |tasklist| %>
  
  <% user = tasklist.user %>
  
    <li class="media">
      <div class="media-left">
        <img class="media-object img-rounded" src="
        <%= graavatar_url(user, options = {size: 50}) %>
        " alt="">
        </div>
        <div class="media-body">
          <div>
            <%= link_to user.name, user_path(user) %>
              <span class="text-muted">posted at 
                <%= tasklist.created_at %>
              </span>
          </div>
          <div>
            <p>
              <%= tasklist.content %>
            </p>
          </div>
          <div>
            <% if current_user == micropost.user %>
            <%= link_to "Delete", micropost, method: :delete, data: { confirm: "You sure?"}, class: 'btn btn-danger btn-xs' %>
            <% end %>
          </div>
        </div>
    </li>
    
    <% end %>
    
    <%= paginate tasklists %>
  
</ul>

<!-- <table class="table table-striped">-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>id</th>-->
<!--      <th>タスク</th>-->
<!--      <th>ステータス</th>-->
<!--    </tr>-->
<!--  </thead>-->
<!--  <tbody>-->
    
<!--<%# @tasklists.each do |tasklist| %>-->
<!--    <tr>-->
<!--      <td>-->
<!--<%#= link_to tasklist.id, tasklist %>       -->
<!--      </td>-->
      
<!--      <td>-->
<!--<%#= tasklist.content %>        -->
<!--      </td>-->
      
<!--      <td>-->
<!--<%#= tasklist.status %>        -->
<!--      </td>-->
<!--    </tr>-->
<!--<%# end %>-->

<!--  </tbody>-->
<!--</table>-->

app/views/tasklists/edit.html.erb
<h1> id:
<%= @tasklist.id %>
のメッセージ編集ページ</h1>

<%=render 'form', tasklist: @tasklist %>

<%= link_to '一覧に戻る', tasklists_path %>

app/views/tasklists/index.html.erb
<% if logged_in? %>
  <p>ログイン完了ユーザ: <%= current_user.name %></p>
  <h1>タスク一覧</h1>

  <% if @tasklists.any? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>id</th>
          <th>ステータス</th>
          <th>タスク</th>
        </tr>
      </thead>
      <tbody>
        <% @tasklists.each do |tasklist| %>
          <tr>
            <td><%= link_to tasklist.id, tasklist %></td>
            <td><%= tasklist.status %></td>
            <td><%= tasklist.content %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div>
      <%= paginate @tasklists %>
    </div>
  <% end %>
  <%= link_to '新規タスクの投稿', new_tasklist_path, class: "btn btn-primary" %>

<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the Tasklist</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/tasklists/new.html.erb
<h1>タスク新規作成ページ</h1>

<%=render 'form', tasklist: @tasklist %>

<%= link_to '一覧に戻る', tasklists_path %>

app/views/tasklists/show.html.erb
<h1> id = <%= @tasklist.id %>のタスク詳細ページ</h1>

<table class="table table-boredered">
  <tr>
    <th>id</th>
    <td>
      <%= @tasklist.id %>
    </td>
  </tr>
  <tr>
    <th>タスク</th>
    <td>
      <%= @tasklist.content %>
    </td>
  </tr>
  <tr>
    <th>ステータス</th>
    <td>
      <%= @tasklist.status %>
    </td>
  </tr>
</table>

<%= link_to '一覧に戻る', tasklists_path, class: 'btn btn-default' %>
<%= link_to 'このメッセージを編集', edit_tasklist_path, class: 'btn btn-default'%>
<%= link_to '削除', @tasklist, method: :delete, data: { confirm:'本当に削除してよろしいですか？'}, class: 'btn btn-danger' %>

app/views/toppages/index.html.erb
<div class="center jumbotron">
  <div class="text-center">
    <h1> Welcome to the Tasklist</h1>
  </div>
</div>

app/views/users/_users.html.erb
<% if users.any?>
  <ul class="media-list">

<% users.each do |user| %>
  <li class="media">
    <div class="media-left">
      <img class="media-object img-rounded" src="
        <%= gravatar_url(user, {size: 50}) %>
        " alt="">
    </div>
    <div class="media-body">
      <div>
        
        <%= user.name %>
      </div>
      <div>
        <p>
          <%= link_to 'View profile', user_path(user) %>
        </p>
      </div>
    </div>
  </li>
  <% end %>
  
  </ul>
  
  <%= paginate users %>
  
  <% end %>

app/views/users/create.html.erb
<%= form_for(@user) do |f| %>

<%= render 'layouts/error_messages', model: f.object %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for(@user) do |f|%>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>

      </div>
      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email,class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
      <% end %>
  </div>
</div>